name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
       distribution: 'temurin'
       java-version: '17'
       cache: 'maven'
    - name: Build with Maven
      run: mvn clean package
    - name: Upload JAR to Windows Server
      uses: appleboy/scp-action@master
      with:
        host: 203.223.112.190
        username: Admin
        password: Xyloite@999
        port: 22 # Adjust port if needed
        source: "target/onlinebookstore.war"  # Path to your JAR file relative to the repository root
        target: "C:\\Users\\Admin\\Documents\\ARUN"  
